version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=cash_register.settings
    depends_on:
      - db

  db:
    image: sqlite
    volumes:
      - ./db.sqlite3:/app/db.sqlite3